#!/usr/bin/env python3
"""make_pymol_compare.py — write per-system PyMOL scripts comparing MD vs generated ensembles.

For each system, emits <ID>_compare.pml that loads the MD ensemble
(results/pdb_md/<ID>_md.pdb, from md2pdb.py) plus one object per model
(results/samples/<dir>/pdb/<ID>.pdb, from samples2pdb.py), aligns everything
to MD frame 1, colors by model, and switches on grid_mode for side-by-side
comparison. Missing PDBs are skipped with a warning in the .pml comment.

Run:  python3 make_pymol_compare.py --systems 2LBS,6TPH,2HGH,7K9D,4M4O
      pymol results/pymol/2LBS_compare.pml        # from anywhere (absolute paths)
"""
import argparse, os

ROOT = os.environ.get("ROOT", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# PyMOL palette (from the project color list); MD gets the teal, models the rest
COLORS = {
    "MD": "0x8bd0d5",
    "NMR": "0xc5e1a3",
    "A": "0xb0a3d1",
    "B": "0xf5a37d",
    "C": "0xe88db2",
}

DEFAULT_MODELS = [
    ("A", "flow_model_r15"),
    ("B", "flow_model_ff"),
    ("C", "flow_model_ff_guided0.1"),
]


def write_pml(pid, models, outdir):
    lines = [
        f"# {pid} ensemble comparison — generated by make_pymol_compare.py",
        "reinitialize",
        "bg_color white",
        "set ray_shadows, 0",
        "set antialias, 2",
        "set cartoon_fancy_helices, 1",
    ]
    loaded = []

    md_p = os.path.join(ROOT, "results", "pdb_md", f"{pid}_md.pdb")
    if os.path.exists(md_p):
        lines.append(f"load {md_p}, MD")
        loaded.append(("MD", "MD"))
    else:
        lines.append(f"# [missing] {md_p} — run md2pdb.py first")

    nmr_p = os.path.join(ROOT, "results", "pdb_nmr", f"{pid}_nmr.pdb")
    if os.path.exists(nmr_p):
        lines.append(f"load {nmr_p}, NMR")
        loaded.append(("NMR", "NMR"))

    for name, d in models:
        p = os.path.join(ROOT, "results", "samples", d, "pdb", f"{pid}.pdb")
        if os.path.exists(p):
            lines.append(f"load {p}, {name}")
            loaded.append((name, name))
        else:
            lines.append(f"# [missing] {p} — run samples2pdb.py --samples results/samples/{d}")

    if not loaded:
        print(f"[skip] {pid}: nothing to load")
        return None

    ref = "MD" if any(o == "MD" for o, _ in loaded) else loaded[0][1]
    lines.append("hide everything")
    lines.append("show cartoon")
    for label, obj in loaded:
        lines.append(f"color {COLORS.get(label, '0xb0a3d1')}, {obj}")
        if obj != ref:
            lines.append(f"align {obj}, {ref}")
    lines += [
        "set all_states, on",
        "set grid_mode, 1",
        "zoom",
        "",
        "# putty view (B-factor = ensemble RMSF):",
        "# cartoon putty",
        "# spectrum b, blue_white_red, minimum=0, maximum=5",
    ]
    out_p = os.path.join(outdir, f"{pid}_compare.pml")
    with open(out_p, "w") as f:
        f.write("\n".join(lines) + "\n")
    return out_p


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--systems", required=True, help="comma-sep PDB IDs")
    ap.add_argument("--models", default="",
                    help="comma-sep name=samples_dir pairs "
                         f"(default: {','.join(f'{n}={d}' for n, d in DEFAULT_MODELS)})")
    ap.add_argument("--out", default=os.path.join(ROOT, "results", "pymol"))
    args = ap.parse_args()

    models = DEFAULT_MODELS
    if args.models:
        models = [tuple(kv.split("=", 1)) for kv in args.models.split(",") if "=" in kv]

    os.makedirs(args.out, exist_ok=True)
    for pid in [s.strip().upper() for s in args.systems.split(",") if s.strip()]:
        out_p = write_pml(pid, models, args.out)
        if out_p:
            print(f"[pml] {pid} -> {out_p}")


if __name__ == "__main__":
    main()
